...
apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: prod
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/name: demo
    app: demo
  sessionAffinity: None
  type: ClusterIP
---
...
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: msa
  namespace: prod
spec:
  encryptedData:
    DB_CONN: AgAs6VydbKkpGM1rOa5hd+8fMISCC/+zNFYQUkM
    SECRET_KEY: AgB7Es8nI0eItJDGErGlK4zA+
  template:
    data: 
    metadata:
      name: demo
      namespace: prod
    type: Opaque
---
...
apiVersion: v1
data:
  AWS_REGION: us-west-2
  aws_regions: us-west-2
  DBNAME: test
  BUCKET: demo

kind: ConfigMap
metadata:
  name: demo
  namespace: prod
---
...
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::accountid-role
  name: demo
  namespace: prod
---
...

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    version: "1.2"
    app: demo
    app.kubernetes.io/name: demo
  name: demo
  namespace: prod
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: demo
      app.kubernetes.io/name: demo
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo
        app.kubernetes.io/name: demo
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - demo
      containers:
        - envFrom:
            - configMapRef:
                name: demo
            - secretRef:
                name: demo
          image: 548244693820.dkr.ecr.us-west-2-imagename # {"$imagepolicy": "flux-system:msa-prod-policy"}
          imagePullPolicy: IfNotPresent
          name: demo
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
            failureThreshold: 8
          readinessProbe:
            failureThreshold: 30
            httpGet:
              path: /
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 40
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 200m
              memory: 350Mi
            limits:
              cpu: 200m
              memory: 350Mi
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            readOnlyRootFilesystem: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: demo
      serviceAccountName: demo
      terminationGracePeriodSeconds: 30
      tolerations:
        - effect: NoSchedule
          key: app
          operator: Equal
          value: demo
---
