apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: demo
  namespace: prod
spec:
  maxReplicas: 10
  minReplicas: 3
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo
  targetCPUUtilizationPercentage: 85

